version: '2'

services:

  nginx:
    image: nginx:1.13.0-alpine
    ports:
      -

  web:
    build: .
    links:
      - redis
    ports:
      - '3003:3003'

  redis:
      image: redis
      ports:
          - "6379:6379"
